### ISSUE TITLE
backend on flask

### ISSUE THREAD

**Issue by achugr** [achugr/goods-review-ng#1]
Посмотри, пожалуйста, пару примеров проектов на http://flask.pocoo.org/ этом фреймворке. Запусти у себя и опиши, пожалуйста 
а) нормальная ли это тема :) 
б) удобно ли писать (нас интересует шаблон + заполнение контентом)
в) как решается проблема общих частей страниц (типа html include-ы), чтобы удобно было переиспользовать всякие шапки, блоки меню и прочее
г) насколько гибкая штука, те сможем ли мы далее развивать на этой базе крутую интерактивность, если захотим (с использованием js в том числе) 
д) удобно ли на базе этой штуки сделать http API? 
Для начала обзорно, если тебе понравится, то начнем копать глубже и пробовать что-нибудь простенькое забацать.

**Comment by batya239** [comment]
про пункт б) 
1. нас интересует заполнение контентом на уровне того, что мы пихнем например им в респонс какой-то класс и чтобы это быстренько в джсончик отобразилось, без гемора
2. нас интересует заполнение контентом и шаблоны только раздельно

**Comment by batya239** [comment]
Артемий пункт г) совсем не в тему помоему, это уж вопрос больше в сторону когда выпустят хтмл версии 100500

**Comment by achugr** [comment]
согласен с замечаниями

**Comment by achugr** [comment]
Дима порефакторил приоритеты, решили сделать позже
