### ISSUE TITLE
обработка данных

### ISSUE THREAD

**Issue by achugr** [achugr/goods-review-ng#10]
Реализовать механизм обработки данных. На нормальном AnalyzingSchedulerTask, переопределив метод process и имплементировать класс EntityUpdater(оболочка для ExtractThesis). 
Илья, Дима, в каком формате и куда пишем извлеченные тезисы? 
Внутрь комментария, или заводим отдельную сущность в базе? 
Пусть тезис будет объектом с полями content, importance, positivity?
Давайте тут все это опишем, после чего сделаем.

**Comment by NlogN** [comment]
Думаю, что нужно заводить отдельную сущность в базе для тезисов. Таким образом не придется усложнять комметарий, который и так имеет сложную структуру.

**Comment by batya239** [comment]
Не надо -- пиши их в ревью и просто uptade его, так проще

**Comment by achugr** [comment]
Я согласен с Димой. 
1) мы всегда знаем что привязка тезисы-отзыв не поедет
2) это просто и бесплатно
3) все равно мы будем показывать комментарии, значит нам надо будет отдать только их, и выдернуть из них тезисы
4) Благодаря такой привязке будет удобно сделать "подсветку" тезиса в комменте
Короче, получается что мы не отнимаем у отзыва его child-а, это кул :)

**Comment by achugr** [comment]
И да, еще один плюс: по факту, мы расширяем апи маркета, добавляя функционал. Это будут минимальные затраты на сервер-сайде. Только на клиенте дописал немного js-а и вуаля, тезисы у тебя тоже есть.

**Comment by achugr** [comment]
Думаю, хранить это можно так
Дописываем внуть объекта review объект "thesis":{"value":"клава отличная", "importance":0.5, "positivity":3}
Вроде того. Никакие поля не забыл? Названия ок?

**Comment by achugr** [comment]
Илья, есть какие проблемы с задачей?
