### ISSUE TITLE
шедулер для майнера

### ISSUE THREAD

**Issue by achugr** [achugr/goods-review-ng#11]
Подрообности будут тут

**Comment by achugr** [comment]
https://github.com/AChugr/goods-review-ng/blob/master/goods-review-magic/src/main/java/ru/goodsreview/analyzer/AnalyzingSchedulerTask.java
По аналогии с этим классом. В run дергаем майнер. Ты все правильно тогда сказал :) Когда заработает - сделаем еще передачу категории в run метод через контекст.

**Comment by achugr** [comment]
Дим, а как сейчас через шедулер сделать? раньше вот мы писали бин для майнера такой https://github.com/AChugr/GoodsReview/blob/master/goodsreview-miner/src/main/resources/beans.xml
а теперь мы ведь не юзаем TimerTask в явном виде

**Comment by batya239** [comment]
отнаследоваться от соотвествующего интерфейса SchedulerTask, записать его в бины, создать соответсвующий столбец в табличке TASK в базе, сконфигурить в бинах -- ru.goodsreview.scheduler.Scheduler

**Comment by Tim239** [comment]
Спасибо Диме! Шедулер для майнера работает! Единственное, что я пока поставил чтобы он один раз запустился - чисто чтобы потестить... А вообще надо решить как часто надо запускать майнер... Мое предложение - сделать 3 шедулера, для 3х различных майнеров - майнера категорий, майнера моделей и майнера отзывов. Майнер категорий может быть запущен один раз ну или очень очень редко (раз в пол года или год), т.к. катеогрии товаров меняются очень редко, майнер моделей товаров почаще - раз в месяц, т.к. могут появляться новые модели товаров, но это тоже не частое явление. И, наконец, чаще всего должны обновляться отзывы - думаю раз в неделю или 2е недели, т.к. отзывы пишут часто. Плюс, наши майнеры поддерживают майн с "опорой" на информацию, которая уже лежит в базе. В общем это надо обсудить :)

**Comment by achugr** [comment]
Тимур, а как понять что они майнятся? Я просто позапускал и в базе, в таблице TASK значение поля last_run не изменяется. При этом, лог майнера товаров не идет в консоль..

**Comment by Tim239** [comment]
Артемий, точно! Это потому, что я поставил SchedulingType ONCE и уже один раз запустил майнершедулер (для теста). last_run не меняется, по этой же причине... Я поменяю SchedulingType на DAY и SchedulingTime на 3, чтобы майнер запускался 3 раза в день и сам не буду запускать шедулер.

**Comment by achugr** [comment]
Ок, понял! Я то думал ONCE - значит однократно при каждом запуске
Отлично, Тимур :)

29 сентября 2012 г., 14:46 пользователь Tim239
notifications@github.comнаписал:

**Comment by Tim239** [comment]
Работает?

**Comment by achugr** [comment]
Да, супер!
