### ISSUE TITLE
Deprecated -- too many heap space required for usage of this class

### ISSUE THREAD

**Issue by achugr** [achugr/goods-review-ng#12]
https://github.com/AChugr/goods-review-ng/blob/master/goods-review-core/src/main/java/ru/goodsreview/core/db/visitor/CategoryHelper.java

Дима верно отметил, что если мы в этот сет наберем 1оо5оо объектов, то нас покарает OutOfMemory.

**Comment by achugr** [comment]
Ярик, когда займешься этим?

**Comment by batya239** [comment]
мне кажется вопрос в другом, зачем это было сделано?

**Comment by achugr** [comment]
Черт, отличный вопрос!
Это штука для проверки работы анализатора. Забираем все отзывы, анализируем, пишем обратно.
Как это нужно делать?

**Comment by YaroslavSkudarnov** [comment]
Скорее всего, я буду тыкать это сегодня вечером/завтра днём.

**Comment by batya239** [comment]
м, если для проверки, то зачем писать обратно?

**Comment by achugr** [comment]
Ну, изначально планировалось только для проверки. Сейчас хочется уже делать сразу нормально, те весь цикл: чтение, обработка, запись модифицированного отзыва обратно.

**Comment by batya239** [comment]
ну так надо наимплементить метод process в AnalyzingSchedulerTask.java, как хочется или как нужно

и наимплементить EntityUpdater.java -- просто делегировав ему EntityService.improveEntities

**Comment by achugr** [comment]
Ярик, ну ты понял :)
Круто, для этого у Димы было уже предусмотрено что нужно, а я думал идти какой-то кривой дорожкой.

**Comment by YaroslavSkudarnov** [comment]
Хм, а как его заимплементить? А то ни одного примера его использования я не вижу.

**Comment by batya239** [comment]
@Override
protected JSONObject process(final JSONObject object) {
    return извлечь_факты_и_пихнуть_их_в_отзыв(object);
}
