### ISSUE TITLE
Презентация на KESW

### ISSUE THREAD

**Issue by achugr** [achugr/goods-review-ng#13]
Надо презентацию общего содержания на английском языке к 1 октября, чтобы 30 она была уже готова и ее можно было просмотреть.

**Comment by achugr** [comment]
http://prezi.com/rrkydnmdtv-6/present/?auth_key=s2ki3fj&follow=fkdf0e1a-yrd

**Comment by Tim239** [comment]
Вот, что пишут по ссылке:
We are sorry...

The presentation you wanted to join either did not exist, or it has already ended.
Please check the URL and come back!

Thank you for your patience,
The Prezi team

**Comment by achugr** [comment]
http://prezi.com/rrkydnmdtv-6/goodsreview-for-kesw/
Á ÔÁË? ×ÏÚÍÏÖÎÏ, ÄÌÑ ÜÔÏÇÏ ÎÁÄÏ ÚÁÒÅÇÉÔÓÑ(ÔÅÍ, ËÔÏ ÅÝÅ ÎÅ), ÚÁÔÏ ÓÍÏÔÒÅÔØ
ÔÏÞÎÏ ×ÓÅÇÄÁ ÍÏÖÎÏ
http://prezi.com/rrkydnmdtv-6/present/?auth_key=zrvtn1s&follow=fkdf0e1a-yrd
×ÏÔ ÔÁË ÍÏÖÎÏ ÐÏËÁ Õ ÍÅÎÑ ÏÔËÙÔÏ ÓÏÅÄÉÎÅÎÉÅ

2012/9/29 Tim239 notifications@github.com

**Comment by achugr** [comment]
ÏÔ ÔÁË ÍÏÖÎÏ ÐÏËÁ Õ ÍÅÎÑ ÏÔËÙÔÏ ÓÏÅÄÉÎÅÎÉÅ, или, если по-русски, "ок"
