### ISSUE TITLE
server на java

### ISSUE THREAD

**Issue by achugr** [achugr/goods-review-ng#15]
Уменьшаем bus-factor + решаем текующую потребность в сервере.
Сервер на java, шаблонизатор - velocity.

**Comment by achugr** [comment]
какая-то жесть, css загружается всегда, но применяется только та, которая прописана пепосредственно в html коде, а не подгружается через тег "линк"

**Comment by achugr** [comment]
поправил

**Comment by batya239** [comment]
а в чем причина была?

**Comment by achugr** [comment]
Если не прописать mimeType="text/css"(по-моему, это можно сделать только на стороне сервера), то браузер не врубается что это css(несмотря на то, что ты ему в атрибутах тега link говоришь, мол это stylesheet). Очень странно.

**Comment by batya239** [comment]
это странно, и должно все таки у клиента прописываться, сервер ничего не должно знать о типе, в идеале вообще статика не через джетти отдается

**Comment by achugr** [comment]
так, кул, сервер рабоает
Спасибо Диме!
