### ISSUE TITLE
Обработать все имеющиеся комментарии

### ISSUE THREAD

**Issue by achugr** [achugr/goods-review-ng#17]
Нужно повытаскивать тезисы из всех имеющихся комментариев

**Comment by Amarchuk** [comment]
среда, 17 октября 2012 г. пользователь Artemij писал:

> Нужно повытаскивать тезисы из всех имеющихся комментариев

Текущим анализатором? Или вручную? Надо писать конкретнее

>  --
> Reply to this email directly or view it on GitHubhttps://github.com/AChugr/goods-review-ng/issues/17.

## 

С уважением, Александр

**Comment by achugr** [comment]
Конечно анализатором. Илья это писал, он, думаю, понял :) Нужно просто запустить и проследить что все корректно обработалось и сложилось в базу. Потому что вот на какой-то фотик у меня отзывы без тезисов совсем. Явно вырубили анализатор рано
