### ISSUE TITLE
отдавать список категорий

### ISSUE THREAD

**Issue by achugr** [achugr/goods-review-ng#23]
в каждый вью нужно передавать список доступных категорий, в которых есть товары

**Comment by Tim239** [comment]
Прости, можешь пояснить?.. Что значит доступные категории? Для каждой категории в маркете есть какие-то товары... Значит надо все категории передавать во все вью?

**Comment by achugr** [comment]
?????????, ?? ??????? ?????? ? ????? ???? ???? ??????. ?? ????? ????, ?
??????? ???????? ??? ????? ? ???????????? :) ??????, ????? ????
???????????.

28 ??????? 2012 ?., 0:38 ???????????? Tim239 notifications@github.com???????:

**Comment by Tim239** [comment]
Еще раз прости пожалуйста... У меня твой ответ в виде вопросительных знаков отобразился... http://postimage.org/image/yjw4wx1kb/ Я попробовал поизменять кодировки, но текст так и не появился... Можешь повторить твой ответ?

**Comment by achugr** [comment]
Ответил вопросом на вопрос)) я предложил пока захардкодить это. и думаю это лучший вариант
