### ISSUE TITLE
Шедулер

### ISSUE THREAD

**Issue by batya239** [achugr/goods-review-ng#3]
Есть специальный модуль уже для этого, есть одна табличка, что он должен уметь -- 
1.запускать таски в отдельном потоке (пул потоков используется для этого)
2. запускать не через ранаблы а через колаблы и получать Future, по которому можно определить таск завершен уже или нет (соотвественнно время писать в базу в поле last_ping_time)
3. при запуске обновляется поле last_run_time
4. bean_name -- какой исполнитель таска запустить (уже есть для этого интерфейс от которого всем надо наследоваться)
5. тип шедулитнга и время -- раз в какой время, например DAYS, 2 или MINUTES, 5
6. params - джсончик с параметрами, которые надо передать в контекст исполнения

да и всю инфу о том когда таск начался, а когда закончился надо писать в отдельную табличку, которую надо сделать еще

**Comment by batya239** [comment]
да и в табичку ТАСК надо добавить новое поле scheduler_name, соответсвенно к классу Scheduler добавится еще одно поле, соответсвенно надо смотреть надо ли запускать таск именно на нем

**Comment by achugr** [comment]
думаю, готово
