### ISSUE TITLE
индексирование

### ISSUE THREAD

**Issue by achugr** [achugr/goods-review-ng#5]
Дим, опиши, пожалуйста, задачу подробнее

**Comment by batya239** [comment]
индексация категорий -- по первой букве в названии (точное совпадение), по названию, по маркетовому id (точное совпадение), по parentId (точное совпадение)
индексация отзывов по -- modelId (точное совпадение), по дате (есть ли возможность сортировки (в сфинксе есть точно)), по pro, по contra, по text

про модели потом, потому что я не читал про них еще

соотвественно модельные классы есть в core

индексировать надо lucene

**Comment by batya239** [comment]
на первый пункт должен был ответить Артемий -- он менеджер, ну да ладно

**Comment by batya239** [comment]
скорее всего надо индексировать не совсем так, как я сказал, но поиск должен быть именно такой + по очевидным причинам версия lucene должна быть 3.6 (не самая новая)

**Comment by achugr** [comment]
Давайте обсудим, какой мы хотим поиск(исходя из этого уже посмотрим, что и как индексировать)..Предлагаю вот что
Базовое:
1) по названию модели (и по id)
2) по названию категории  (и по id)
3) по тезису  (и по id)
4) по отзыву (не слишком ли много индексировать?) мы как раз делаем выжимку сути, так что поиска по всему комментарию можно избежать, думаю. Просто не очень понимаю, что нам это даст. Вот человек пишет "отличный ноут" - ну так это в тезисах есть, их и индексируем.
Опционально:
1) по первой букве категории (не думаю, что поиск по алфавиту так уж удобен, думаю, для базового функционала он нам не нужен)

**Comment by achugr** [comment]
индексирование временно подзамораживаем, чтобы выкатить продакшн побыстрее

**Comment by achugr** [comment]
Хрена с два мы выкатим что-то без пусть даже простого индекса. Надо сделать.
База:
По id модели получать ее описание
По имени модели получать ее описание
По id модели получать отзывы на модель
По id категории получать список моделей категории(причем очень желательно уметь его получать по частям, думаю можно это сделать так: некоторая логика в индексере, которая проходит по товарам определенной категории, смотрит их popularity, сортирует и группирует в сеты по N товаров, каждый такой сет + id сета пихается в Document lucene. На сайте будет перечисление страниц, типа 1->2->... вот это и будут id сетов). 

Сделаем слева небольшой список категорий, даже не дерево, а просто список
При клике на категорию будет открываться страница с перечислением товаров категории
При клике на товар будет открываться его страница + отзывы.
По названию товара можно сделать текстовый поиск, если я правильно понимаю.

**Comment by batya239** [comment]
не нужен пока индексер, тупая обертка над мускулем, работающая очень криво подойдет

**Comment by achugr** [comment]
Что такое обертка над мускулем?
У нас 4к товаров, вытащить инфу о товаре по его маркетовому id - примерно 20 секунд. Это не очень тру) Правда, я делал поиск через java, может если сделать какой-нибудь мускульный запрос с contains string или чем-то таким, то получится быстрее, но все же.

**Comment by batya239** [comment]
есть тема например в оракле (думаю тут тоже есть) some_param like '%your_query%'

**Comment by achugr** [comment]
ну да, типа select \* from ENTITY where ENTITY_ATTRS like '%id=123456%', вроде того, да?

**Comment by achugr** [comment]
ок, таким способом уходит 2-3 секунды
если конечно мускуль там у себя что-то не закешировал, утром проверю еще раз
это уже не смертельно, но неприятно
терпимо)

**Comment by achugr** [comment]
Ладно, пока потребность временно отпала - закроем.
